### ISSUE TITLE
MMKV and Redux plugin types do not match the new `reactotron-react-native` types

### ISSUE THREAD

**Issue by renchap** [infinitered/reactotron#1391]
```ts
import Reactotron from "reactotron-react-native"
import mmkvPlugin from "reactotron-react-native-mmkv"
import { reactotronRedux } from "reactotron-redux"

import { mmkvStorage } from "./mmkv_storage"

export const reactotron = Reactotron.configure({
  name: "Notos",
})
  .use(mmkvPlugin({ storage: mmkvStorage })),
  .use(reactotronRedux())
  .connect()
```

Has 2 Typescript errors:

```
Argument of type '(reactotron: Reactotron) => { onConnect(): void; onDisconnect(): void; }' is not assignable to parameter of type 'PluginCreator<ReactotronReactNative>'.
  Types of parameters 'reactotron' and 'client' are incompatible.
    Type 'ReactotronReactNative' is not assignable to type 'Reactotron'.
      Types of property 'options' are incompatible.
        Type 'ClientOptions<ReactotronReactNative>' is not assignable to type 'ClientOptions<Reactotron>'.
          Type 'Reactotron' is missing the following properties from type 'ReactotronReactNative': useReactNative, setAsyncStorageHandler, trackAsyncStorage, untrackAsyncStoragets
Argument of type '(reactotron: Reactotron) => { onCommand: ({ type, payload }: { type: string; payload?: any; }) => void; features: { createEnhancer: (skipSettingStore?: boolean | undefined) => (createStore: any) => (reducer: any, ...args: any[]) => any; setReduxStore: (store: any) => void; reportReduxAction: (action: { ...; }, ms: n...' is not assignable to parameter of type 'PluginCreator<ReactotronReactNative>'.
  Types of parameters 'reactotron' and 'client' are incompatible.
    Type 'ReactotronReactNative' is not assignable to type 'Reactotron'.ts(2345)

**Comment by ellaschwarz** [comment]
I have the same issue!

**Comment by hannahct** [comment]
Hitting the same issue

**Comment by ellaschwarz** [comment]
Thanks for the fix! That typescript error is not showing after upgrading to 3.1.5, but now I get this instead: 
_Property 'createEnhancer' does not exist on type 'Reactotron<ReactotronReactNative> & ReactotronReactNative'._

**Comment by rdnsan** [comment]
> Thanks for the fix! That typescript error is not showing after upgrading to 3.1.5, but now I get this instead: _Property 'createEnhancer' does not exist on type 'Reactotron & ReactotronReactNative'._

same issue
